### ISSUE TITLE
Installation problem - solved - install Git, do not run 'npm audit fix'

### ISSUE THREAD

**Issue by felixunivers** [johnpapa/angular-ngrx-data#223]
I was trying to install and run, but got errors:

```
ERR! code ELIFECYCLE
ERR! errno 1
ERR! angular-ngrx-data@0.6.2 snyk-protect: `snyk protect`
ERR! Exit status 1
npm ERR!
ERR! Failed at the angular-ngrx-data@0.6.2 snyk-protect script.
ERR! This is probably not a problem with npm. There is likely additional logging output above.

ERR! code ELIFECYCLE
ERR! errno 1
ERR! angular-ngrx-data@0.6.2 prepare: `npm run snyk-protect`
ERR! Exit status 1
npm ERR!
ERR! Failed at the angular-ngrx-data@0.6.2 prepare script.
ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Solved later as follows:

Steps to resolve: 

 - Install   Git: Git-2.21.0-64-bit.exe
   from:   [https://git-scm.com/download/win](https://git-scm.com/download/win)

 - Mind getting the installation directory !

 - in it find Git file:  patch.exe
   (e.g: C:\Users\me\AppData\Local\Programs\Git\usr\bin
    or: C:\Program Files\Git\usr\bin
    or so ...)

 - add its full path/directory to  %PATH% - Windows environment variable.

 - restart PowerShell (or Command terminal)

 - follow the installation steps from start

**Comment by felixunivers** [comment]
It appears we still have an issue - on command: ng s -o 
I get a stack of errors - below. I think at this point I need some input - thank you. 

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output has an unknown property 'futureEmitAssets'. These properties are valid:
   object { auxiliaryComment?, chunkFilename?, webassemblyModuleFilename?, globalObject?, crossOriginLoading?, jsonpScriptType?, chunkLoadTimeout?, devtoolFallbackModuleFilenameTemplate?, devtoolLineToLine?, devtoolModuleFilenameTemplate?, devtoolNamespace?, filename?, hashDigest?, hashDigestLength?, hashFunction?, hashSalt?, hotUpdateChunkFilename?, hotUpdateFunction?, hotUpdateMainFilename?, jsonpFunction?, chunkCallbackName?, library?, libraryTarget?, libraryExport?, path?, pathinfo?, publicPath?, sourceMapFilename?, sourcePrefix?, strictModuleExceptionHandling?, umdNamedDefine? }
   -> Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output has an unknown property 'futureEmitAssets'. These properties are valid:
   object { auxiliaryComment?, chunkFilename?, webassemblyModuleFilename?, globalObject?, crossOriginLoading?, jsonpScriptType?, chunkLoadTimeout?, devtoolFallbackModuleFilenameTemplate?, devtoolLineToLine?, devtoolModuleFilenameTemplate?, devtoolNamespace?, filename?, hashDigest?, hashDigestLength?, hashFunction?, hashSalt?, hotUpdateChunkFilename?, hotUpdateFunction?, hotUpdateMainFilename?, jsonpFunction?, chunkCallbackName?, library?, libraryTarget?, libraryExport?, path?, pathinfo?, publicPath?, sourceMapFilename?, sourcePrefix?, strictModuleExceptionHandling?, umdNamedDefine? }
   -> Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
    at webpack (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\webpack\lib\webpack.js:24:9)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-webpack\src\webpack-dev-server\index.js:39:37)
    at Observable._trySubscribe (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-webpack\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-webpack\node_modules\rxjs\internal\Observable.js:30:22)
    at C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\util\subscribeToObservable.js:10:20
    at Object.subscribeToResult (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at MergeMapSubscriber._innerSub (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\mergeMap.js:76:14)
    at MergeMapSubscriber._next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:67:18)
    at TapSubscriber._next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\tap.js:65:26)
    at TapSubscriber.Subscriber.next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:67:18)
    at SafeSubscriber.__tryOrUnsub (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\rxjs\internal\Subscriber.js:263:16)
    at SafeSubscriber.next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\rxjs\internal\Subscriber.js:201:22)
    at Subscriber._next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\rxjs\internal\Subscriber.js:139:26)
    at Subscriber.next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\rxjs\internal\Subscriber.js:103:18)
    at SafeSubscriber.__tryOrUnsub (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:209:16)
    at SafeSubscriber.next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:147:22)
    at MergeMapSubscriber.notifyNext (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:67:18)
    at SafeSubscriber.__tryOrUnsub (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\rxjs\internal\Subscriber.js:263:16)
    at SafeSubscriber.next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\rxjs\internal\Subscriber.js:201:22)
    at Subscriber._next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\rxjs\internal\Subscriber.js:139:26)
    at Subscriber.next (C:\E\Data\projects\dev\angular\examples\angular-ngrx-data\node_modules\rxjs\internal\Subscriber.js:103:18)
```
